CREATE TYPE poker_user_role AS ENUM ('Front End Dev', 'QAE', 'Team Lead');

CREATE TABLE poker_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  role poker_user_role NOT NULL,
  password TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);
